### ISSUE TITLE
Generic subroutine 'lu_resolucion' at (1) is not consistent with a specific subroutine interface

### ISSUE THREAD

**Issue by andonizaballa** [enekomateos/konproiektu#15]
Programa ejekutatzean hau ematen du Fortranek. Matrize eta termino independenteen dimentsioak berdinak dira **(shape(A) --> 460,460 / shape(B) --> 460)** asi que ez dakit zergatik ez duen ondo egiten.

**Comment by andonizaballa** [comment]
gaussj-k errore berdina ematen du

**Comment by enekomateos** [comment]
Errorea soluzionau dot baina oin arazua da gure A matrizean determinantia dala 0 jajajajaja

**Comment by enekomateos** [comment]
Gauza zan gaussj erabiltzerakuen b matrize bat izen bie zala, ez bektore bat

**Comment by andonizaballa** [comment]
🙃

**Comment by enekomateos** [comment]
Bale egon naz matrizia begiratzen goitik behera ta arazua nik uste dauela phi funtzioan

**Comment by enekomateos** [comment]
Berridatziot phi lehenengo bi direkziuak batzeko ta gero horren norma kalkulatzeko ta oin no da lehenauko erroria... tiene mas sentido baina ez dot ulertzen lehenaukuak zeba ezauen ondo funtzionetan

**Comment by andonizaballa** [comment]
Ba ez dakit... Fortran's things.
