### ISSUE TITLE
Phi zenbaki edo funtzio moduen L-n

### ISSUE THREAD

**Issue by enekomateos** [enekomateos/konproiektu#7]
L-ren funtzioa sortzean phi sartu leike zenbaki bat moduen edo funtzio moduen. Berez interesetan jakuna da phi_ij zenbakixa baina igual txukunaua da sartzia L-n funtzio moduen. Alatabe ein leike gorde kanpoko programan phi-ren balioa eta gero berrerabili eta hola ez da kalkulau biher phi bi aldiz eta suposatzeot "efizientiaua" izengo dala

**Comment by andonizaballa** [comment]
Nik funtzio moduan jarriko nuke

**Comment by enekomateos** [comment]
Balee ba decididoo :) gainea ikusiot aldatuzula ya asik asi se queda
